### ISSUE TITLE
Compiling error RF24.h: No such file or directory

### ISSUE THREAD

**Issue by HenkSnavel** [hencou/esphome-milight#11]
Error while compiling.
Used your example yaml and same issue.

INFO Reading configuration /config/esphome/test.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing mitest1 (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Library Manager: Installing git+https://github.com/hencou/esphome-milight
git version 2.30.2
Cloning into '/data/cache/platformio/cache/tmp/pkg-installing-bk8ukqhh'...
Library Manager: milight @ 0.0.2+sha.3fe8d4c has been installed!
Library Manager: Installing dependencies...
Library Manager: Installing SPI @ *
Warning! Please upgrade to the PlatformIO Core 6
Library Manager: Installing git+https://github.com/luisllamasbinaburo/Arduino-List
git version 2.30.2
Cloning into '/data/cache/platformio/cache/tmp/pkg-installing-p7i05s35'...
Library Manager: ListLib @ 1.0.0+sha.a250c6e has been installed!
Dependency Graph
|-- <milight> 0.0.2+sha.3fe8d4c
|   |-- <SPI> 1.0
|   |-- <ArduinoJson> 6.18.5
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|-- <ListLib> 1.0.0+sha.a250c6e
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/api/api_connection.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/api/api_frame_helper.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/api/api_pb2.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/api/api_pb2_service.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/api/api_server.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/api/list_entities.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/api/proto.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/api/subscribe_state.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/api/user_services.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/binary_sensor/automation.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/binary_sensor/filter.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/button/button.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/esp8266/core.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/esp8266/gpio.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/esp8266/preferences.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/light/addressable_light.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/light/automation.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/light/esp_color_correction.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/light/esp_hsv_color.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/light/esp_range_view.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/light/light_call.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/light/light_json_schema.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/light/light_output.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/light/light_state.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/logger/logger.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/md5/md5.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/mdns/mdns_component.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/mdns/mdns_esp32_arduino.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/mdns/mdns_esp_idf.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/mi/button/mi_button.cpp.o
Compiling /data/mitest1/.pioenvs/mitest1/src/esphome/components/mi/light/mi_light.cpp.o
In file included from src/esphome/components/mi/mi.h:8,
                 from src/esphome/components/mi/button/mi_button.h:4,
                 from src/esphome/components/mi/button/mi_button.cpp:2:
/data/mitest1/.piolibdeps/mitest1/milight/src/lib/Radio/PL1167_nRF24.h:12:10: fatal error: RF24.h: No such file or directory

**************************************************************
* Looking for RF24.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:RF24.h"
* Web  > https://registry.platformio.org/search?q=header:RF24.h
*
**************************************************************

   12 | #include "RF24.h"
      |          ^~~~~~~~
compilation terminated.
*** [/data/mitest1/.pioenvs/mitest1/src/esphome/components/mi/button/mi_button.cpp.o] Error 1
In file included from src/esphome/components/mi/mi.h:8,
                 from src/esphome/components/mi/button/mi_button.h:4,
                 from src/esphome.h:46,
                 from src/esphome/components/mi/light/mi_light.cpp:1:
/data/mitest1/.piolibdeps/mitest1/milight/src/lib/Radio/PL1167_nRF24.h:12:10: fatal error: RF24.h: No such file or directory

**************************************************************
* Looking for RF24.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:RF24.h"
* Web  > https://registry.platformio.org/search?q=header:RF24.h
*
**************************************************************

   12 | #include "RF24.h"
      |          ^~~~~~~~
compilation terminated.
*** [/data/mitest1/.pioenvs/mitest1/src/esphome/components/mi/light/mi_light.cpp.o] Error 1
========================= [FAILED] Took 19.79 seconds =========================

**Comment by hencou** [comment]
Hi Henk, can you share your config yaml?

**Comment by HenkSnavel** [comment]
It had the same error if i use your "demo" yaml.

I already deleted all files in the external_components and build folder to get a fresh compile

**Comment by HenkSnavel** [comment]
Found out i used a old version of ESPhome (03.2022)
Updated esphome and library was found in new version

**Comment by hencou** [comment]
Ah nice you found it ;-)
